### ISSUE TITLE
About xtract-feature package installation

### ISSUE THREAD

**Issue by Mozihua** [SIAAAAAA/CGC-Net#1]
Hi Yanning,

I cannot find the 'xtract-feature' package in pip installation which is refered in 'nuc_feature.py'.
Where can I install this package.

Thanks

**Comment by Amandaynzhou** [comment]
@Mozihua 
Hi, you can find the package here [https://github.com/vatsalsaglani/xrayimage_extractfeatures](https://github.com/vatsalsaglani/xrayimage_extractfeatures). Hope it helps.

**Comment by Mozihua** [comment]
Thank you very much.

发自我的iPhone

------------------ Original ------------------
