### ISSUE TITLE
Does the code divides the images into patches?

### ISSUE THREAD

**Issue by cruyffturn** [SIAAAAAA/CGC-Net#3]
In the paper, it's stated that:

> We extract patches with a size of 1792x1792

Do you expect the user to divide the images into patches or should I organize the folders without dividing the images into patches?

Thank you for sharing the code.

**Comment by Amandaynzhou** [comment]
@cruyffturn Hi! We pre-process the larger ROI images (patient-level) into patches with the resolution of 1792*1792 and store them in folders.

**Comment by cruyffturn** [comment]
@SIAAAAAA Thank you. Can you clarify once again whether this code automatically pre-process the images into patches or not? If's not automatic is there a naming convention that I need to follow for the image level performance metrics to work?

Thank you so much.

**Comment by Amandaynzhou** [comment]
Hi @cruyffturn, sorry for the late reply!
Attached please find the name of files we use as patches. Thanks.
[https://drive.google.com/file/d/1_lA3YuwUrMmi2WKT2AN-GrPTmKSY3KDc/view?usp=sharing](url)

**Comment by cruyffturn** [comment]
Thank you!

**Comment by PrinceEAdjei** [comment]
The link does not work. Any help @cruyffturn @SIAAAAAA
